# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/jessie64"

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  config.vm.provision "shell", inline: <<-SHELL
    APTPROXY="configserver01"
    echo "Checking for apt proxy $APTPROXY"
    if ping -c 1 $APTPROXY > /dev/null; then
        echo "- Using apt-proxy $APTPROXY"
        echo 'Acquire::http::Proxy "http://'$APTPROXY':9999";' > /etc/apt/apt.conf.d/55aptproxy
    else
        echo "- Not using apt-proxy $APTPROXY"
    fi
   SHELL
end
